[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "profecia"
version = "0.1.0"
description = "Configuración, preprocesado, modelado e interpretación de datos ambientales y LAI"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    {name = "garciad"}
]

dependencies = [
    "numpy",
    "pandas",
    "xarray",
    "netcdf4",
    "h5netcdf",
    "dask",
    "matplotlib",
    "pillow",
    "scipy",
    "statsmodels",
    "scikit-learn==1.8.0",
    "shap",
    "seaborn",
    "geopandas",
    "ipywidgets",
    "ipyleaflet",
    "ipykernel",
    "jupyter",
    "jupyterlab",
    "notebook",
    "tomli; python_version < '3.11'",
    "tomli-w",
    "mlflow",
    ]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
