[project]
main_dir = "/mnt_sentinel_a/ferag/data" 
raw_dir = "/srv/read_only_data/final_datasets/monthly/"
processed_base_dir = "/home/ubuntu/data/processed"
mask_dir = "/srv/read_only_data/final_datasets/masks"

[data]
temporal_resolution = "annual"
mask_names = ["land", "ebf", "bs"]
start_year = 1982
end_year_inclusive = 2022
dtype = "float32"
variable_names = ['LAI', 'CO2', "HFP", "NDEP", "TLU", 'SM1', 'SM1_LAG_1', 'SM2', 'SM2_LAG_1', 'TP', 'TP_LAG_1', 'T2M', 'T2M_LAG_1', 'SSRD','VPD', 'D2M',  'PEV', 'SSRD_LAG_1','VPD_LAG_1', 'D2M_LAG_1',  'PEV_LAG_1',  'LC_STATIC']
target_name = "LAI"

# roi = { lat_min = -60.0, lat_max = 80.0, lon_min = -180.0, lon_max = 180.0 }

[mlflow]
enabled = true
tracking_uri = "https://mlflow.cloud.ai4eosc.eu/"
tracking_username = "aguilarf@ifca.unican.es"
tracking_password = "saintGenis@17"
experiment_name = "annual_1982_2022_rf_with_human_and_few_lag"
