[data]
temporal_resolution = "annual"
data_value_type = "trend"
mask_names = [
    "land",
]
start_year = 1988
end_year_inclusive = 2010
dtype = "float32"
variable_names = [
    "LAI",
    "SM1",
    "SM1_2",
    "TP",
    "D2M",
    "WIND",
    "CO2",
    "NDEP",
    "PH",
    "RICHNESS",
    "BULK",
]
target_name = "LAI"

[data.roi]
lat_min = -60.0
lat_max = 60.0
lon_min = -180.0
lon_max = 180.0

[data.categorical_filters]
climate = []
landcover = []
