[project]
main_dir = "/home/dani/github/profecia/data"
raw_dir = "/home/dani/github/profecia/data/raw"
processed_base_dir = "/home/dani/github/profecia/data/processed"
# mask_dir = "/home/dani/github/profecia/data/masks"

[data]
temporal_resolution = "monthly" # "monthly" o "annual"
data_value_type = "anomaly" # "real" o "anomaly"
detrend_theil_sen = false
mask_names = ["land"] # ["land"]
start_year = 1982
end_year_inclusive = 2022
dtype = "float32"
variable_names = ['LAI', 'SM1', 'SM2',  'TP', 'T2M', 'SSRD', 'VPD', 'D2M', 'PEV']
target_name = "LAI"

# roi = { lat_min = -60.0, lat_max = 80.0, lon_min = -180.0, lon_max = 180.0 }
# Si no se define, se usa todo el globo disponible.

[mlflow]
enabled = false
tracking_uri="https://mlflow.cloud.ai4eosc.eu/"
tracking_username="aguilarf@ifca.unican.es"
tracking_password=""
experiment_name="land_without_lag"
